#!/usr/bin/env bash
# Gaming Community in a Box — Phase 2: Setup Wizard
# Customer runs this on first SSH login (via `evlbox setup`).
# TUI wizard (whiptail) collects config, picks optional services, and starts everything.

set -euo pipefail

STACK_DIR="/opt/evlbox/stack"
STOAT_DIR="/opt/evlbox/stoat"
ENV_FILE="$STACK_DIR/.env"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Please run as root: sudo evlbox setup"
        exit 1
    fi
}

check_whiptail() {
    if ! command -v whiptail &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq whiptail
    fi
}

has_profile() {
    [[ ",$PROFILES," == *",$1,"* ]]
}

get_server_ip() {
    hostname -I | awk '{print $1}'
}

# Validate that a URL does NOT contain a path (for apps that require subdomain)
validate_subdomain_only() {
    local url="$1"
    local app_name="$2"
    if [[ "$url" == *"/"* ]]; then
        whiptail --title "Invalid URL" --msgbox \
        "${app_name} requires its own subdomain and cannot run on a subpath.\n\n\
Example: chat.example.com (good)\n\
Example: example.com/chat (not supported)\n\n\
Please try again." 12 60
        return 1
    fi
    return 0
}

# Generate Caddyfile from per-service URL variables
generate_caddyfile() {
    local caddyfile="$STACK_DIR/templates/Caddyfile"

    cat > "$caddyfile" << 'HEADER'
# Gaming Community in a Box — Caddyfile
# Generated by setup.sh — do not edit directly.
# Re-run `evlbox setup` to regenerate.
HEADER

    # --- IP-only mode: single site block with self-signed TLS ---
    if [ "$IP_ONLY" = true ]; then
        cat >> "$caddyfile" << EOF

:443 {
	tls internal
	reverse_proxy stoat-caddy:80
}

:80 {
	reverse_proxy stoat-caddy:80
}
EOF
        return
    fi

    # --- Domain mode ---

    # Root domain — points to Stoat or Ghost depending on config
    if [ -n "${ROOT_URL:-}" ]; then
        if [ "$ROOT_TARGET" = "ghost" ]; then
            cat >> "$caddyfile" << EOF

${ROOT_URL} {
	reverse_proxy ghost:2368
}
EOF
        else
            cat >> "$caddyfile" << EOF

${ROOT_URL} {
	reverse_proxy stoat-caddy:80
}
EOF
        fi
    fi

    # Stoat chat subdomain (skip if same as ROOT_URL to avoid duplicate block)
    if [ "${STOAT_URL}" != "${ROOT_URL:-}" ]; then
        cat >> "$caddyfile" << EOF

${STOAT_URL} {
	reverse_proxy stoat-caddy:80
}
EOF
    fi

    # --- Forum (Flarum) — supports subdomain or subpath ---
    if has_profile "forum"; then
        if [[ "$FORUM_URL" == *"/"* ]]; then
            # Subpath mode: extract host and path
            local forum_host="${FORUM_URL%%/*}"
            local forum_path="/${FORUM_URL#*/}"
            cat >> "$caddyfile" << EOF

${forum_host} {
	handle_path ${forum_path}* {
		reverse_proxy flarum:8000
	}
}
EOF
        else
            cat >> "$caddyfile" << EOF

${FORUM_URL} {
	reverse_proxy flarum:8000
}
EOF
        fi
    fi

    # --- Ghost (blog) — subdomain only ---
    if has_profile "blog" && [ -n "${GHOST_URL:-}" ] && [ "${GHOST_URL}" != "${ROOT_URL:-}" ]; then
        cat >> "$caddyfile" << EOF

${GHOST_URL} {
	reverse_proxy ghost:2368
}
EOF
    fi

    # --- Zipline (screenshots) — subdomain only ---
    if has_profile "screenshots"; then
        cat >> "$caddyfile" << EOF

${ZIPLINE_URL} {
	reverse_proxy zipline:3000
}
EOF
    fi

    # --- PrivateBin (paste) — supports subdomain or subpath ---
    if has_profile "paste"; then
        if [[ "$PASTE_URL" == *"/"* ]]; then
            local paste_host="${PASTE_URL%%/*}"
            local paste_path="/${PASTE_URL#*/}"
            cat >> "$caddyfile" << EOF

${paste_host} {
	handle_path ${paste_path}* {
		reverse_proxy privatebin:8080
	}
}
EOF
        else
            cat >> "$caddyfile" << EOF

${PASTE_URL} {
	reverse_proxy privatebin:8080
}
EOF
        fi
    fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
check_root
check_whiptail

cd "$STACK_DIR"

TERM=ansi
export TERM

whiptail --title "EVLBOX — Gaming Community in a Box" --msgbox \
"Welcome! This wizard will set up your gaming community server.\n\n\
You'll pick which services to run, configure your domain,\n\
and everything will be up and running in a few minutes.\n\n\
Includes: Stoat chat, forums, voice, image hosting, and more." 12 65

# =============================================================================
# SERVICE SELECTION (before domain, so we know what needs URLs)
# =============================================================================
SELECTED=$(whiptail --title "Choose Your Services" --checklist \
"Stoat (chat) is always installed. Pick your extras:\n\
Use SPACE to toggle, ENTER to confirm." 18 65 5 \
"forum"         "Flarum — Community forum"              ON \
"voice"         "Mumble — Low-latency voice chat"       ON \
"screenshots"   "Zipline — Screenshot & image hosting"  ON \
"paste"         "PrivateBin — Encrypted paste service"  ON \
"blog"          "Ghost — Community blog / news"          OFF \
3>&1 1>&2 2>&3) || true

# Parse selections into comma-separated profile list
PROFILES=""
for item in $SELECTED; do
    item=$(echo "$item" | tr -d '"')
    if [ -z "$PROFILES" ]; then
        PROFILES="$item"
    else
        PROFILES="$PROFILES,$item"
    fi
done

# If nothing selected, that's fine — just Stoat
if [ -z "$PROFILES" ]; then
    whiptail --title "Minimal Install" --msgbox \
    "No optional services selected.\n\
Only Stoat (chat) will be installed.\n\
You can enable services later with: evlbox enable <service>" 10 60
fi

# =============================================================================
# DOMAIN & ROUTING (after service selection)
# =============================================================================
SERVER_IP=$(get_server_ip)
IP_ONLY=false
DOMAIN=""

# Initialize per-service URL variables
STOAT_URL=""
FORUM_URL=""
GHOST_URL=""
ZIPLINE_URL=""
PASTE_URL=""
ROOT_URL=""
ROOT_TARGET="stoat"

# --- Step 1: Do you have a domain? ---
DOMAIN_CHOICE=$(whiptail --title "Domain Configuration" --menu \
"How would you like to access your services?" 14 65 2 \
"domain" "I have a domain (or will set one up)" \
"ip"     "No domain — IP-only mode" \
3>&1 1>&2 2>&3) || true

if [ "$DOMAIN_CHOICE" = "ip" ]; then
    IP_ONLY=true
    DOMAIN="$SERVER_IP"
    STOAT_URL="$SERVER_IP"
    # IP-only: disable all optional services, only Stoat runs
    PROFILES=""
    whiptail --title "IP-Only Mode" --msgbox \
"IP-only mode: only Stoat (chat) will run at https://${SERVER_IP}\n\
Other services need a domain for subdomain routing.\n\n\
Options to get a domain:\n\
  - Point your own domain at this IP\n\
  - EVLBOX customers: request a free yourname.evlbox.net\n\
    subdomain at https://evlbox.com/help\n\n\
Run 'evlbox setup' again after adding a domain to\n\
enable all services." 16 65
fi

# --- Step 2: Express or Custom? (only if they have a domain) ---
if [ "$IP_ONLY" = false ]; then
    ROUTING_MODE=$(whiptail --title "Routing Setup" --menu \
"How would you like to configure service URLs?" 12 65 2 \
"express" "Express setup (recommended) — auto-assign subdomains" \
"custom"  "Custom — choose URLs for each service" \
3>&1 1>&2 2>&3) || true

    # --- Express mode ---
    if [ "$ROUTING_MODE" = "express" ]; then
        DOMAIN=$(whiptail --title "Express Setup" --inputbox \
"Enter your domain (e.g., myguild.com):" 10 60 "" 3>&1 1>&2 2>&3) || true

        if [ -z "$DOMAIN" ]; then
            whiptail --title "Error" --msgbox "Domain cannot be empty." 8 40
            exit 1
        fi

        # Auto-assign subdomains
        STOAT_URL="chat.${DOMAIN}"
        has_profile "forum"        && FORUM_URL="forum.${DOMAIN}"
        has_profile "screenshots"  && ZIPLINE_URL="img.${DOMAIN}"
        has_profile "paste"        && PASTE_URL="paste.${DOMAIN}"

        if has_profile "blog"; then
            GHOST_URL="${DOMAIN}"
            ROOT_URL="${DOMAIN}"
            ROOT_TARGET="ghost"
        else
            ROOT_URL="${DOMAIN}"
            ROOT_TARGET="stoat"
        fi

        # Build DNS records message
        DNS_MSG="Create these DNS records pointing to ${SERVER_IP}:\n\n"
        DNS_MSG+="  A  ${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="  A  chat.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "forum"        && DNS_MSG+="  A  forum.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "screenshots"  && DNS_MSG+="  A  img.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "paste"        && DNS_MSG+="  A  paste.${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="\nOr use a wildcard:\n"
        DNS_MSG+="  A  *.${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="  A  ${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="\nCaddy will retry automatically if DNS isn't ready yet."

        whiptail --title "DNS Records Required" --msgbox "$DNS_MSG" 22 65

    # --- Custom mode ---
    elif [ "$ROUTING_MODE" = "custom" ]; then
        DOMAIN=$(whiptail --title "Base Domain" --inputbox \
"Enter your base domain (used for SSL and routing):" 10 60 "" 3>&1 1>&2 2>&3) || true

        if [ -z "$DOMAIN" ]; then
            whiptail --title "Error" --msgbox "Domain cannot be empty." 8 40
            exit 1
        fi

        # Stoat — subdomain required
        while true; do
            STOAT_URL=$(whiptail --title "Stoat Chat [subdomain required]" --inputbox \
"Enter URL for Stoat chat.\n\
Stoat MUST have its own subdomain (no subpaths).\n\n\
Example: chat.${DOMAIN}" 12 60 "chat.${DOMAIN}" 3>&1 1>&2 2>&3) || true
            validate_subdomain_only "$STOAT_URL" "Stoat" && break
        done

        # Forum (Flarum) — subdomain or subpath
        if has_profile "forum"; then
            FORUM_URL=$(whiptail --title "Flarum Forum [subdomain or subpath]" --inputbox \
"Enter URL for Flarum forum.\n\
Supports subdomain OR subpath.\n\n\
Examples: forum.${DOMAIN} or ${DOMAIN}/forum" 12 60 "forum.${DOMAIN}" 3>&1 1>&2 2>&3) || true
        fi

        # Ghost — subdomain required
        if has_profile "blog"; then
            while true; do
                GHOST_URL=$(whiptail --title "Ghost Blog [subdomain required]" --inputbox \
"Enter URL for Ghost blog.\n\
Ghost MUST have its own subdomain (no subpaths).\n\n\
Example: ${DOMAIN} or blog.${DOMAIN}" 12 60 "${DOMAIN}" 3>&1 1>&2 2>&3) || true
                validate_subdomain_only "$GHOST_URL" "Ghost" && break
            done
        fi

        # Zipline — subdomain required
        if has_profile "screenshots"; then
            while true; do
                ZIPLINE_URL=$(whiptail --title "Zipline Images [subdomain required]" --inputbox \
"Enter URL for Zipline image hosting.\n\
Zipline MUST have its own subdomain (no subpaths).\n\n\
Example: img.${DOMAIN}" 12 60 "img.${DOMAIN}" 3>&1 1>&2 2>&3) || true
                validate_subdomain_only "$ZIPLINE_URL" "Zipline" && break
            done
        fi

        # PrivateBin — subdomain or subpath
        if has_profile "paste"; then
            PASTE_URL=$(whiptail --title "PrivateBin Paste [subdomain or subpath]" --inputbox \
"Enter URL for PrivateBin.\n\
Supports subdomain OR subpath.\n\n\
Examples: paste.${DOMAIN} or ${DOMAIN}/paste" 12 60 "paste.${DOMAIN}" 3>&1 1>&2 2>&3) || true
        fi

        # Determine root domain target
        if has_profile "blog" && [ "$GHOST_URL" = "$DOMAIN" ]; then
            ROOT_URL="$DOMAIN"
            ROOT_TARGET="ghost"
        else
            ROOT_URL="$DOMAIN"
            ROOT_TARGET="stoat"
        fi

        # Collect all unique hostnames for DNS records
        DNS_MSG="Create these DNS records pointing to ${SERVER_IP}:\n\n"
        declare -A dns_hosts
        dns_hosts["$DOMAIN"]=1
        dns_hosts["${STOAT_URL}"]=1
        [ -n "$FORUM_URL" ] && dns_hosts["${FORUM_URL%%/*}"]=1
        [ -n "$GHOST_URL" ] && dns_hosts["${GHOST_URL}"]=1
        [ -n "$ZIPLINE_URL" ] && dns_hosts["${ZIPLINE_URL}"]=1
        [ -n "$PASTE_URL" ] && dns_hosts["${PASTE_URL%%/*}"]=1

        for host in "${!dns_hosts[@]}"; do
            DNS_MSG+="  A  ${host}  →  ${SERVER_IP}\n"
        done
        DNS_MSG+="\nCaddy will retry automatically if DNS isn't ready yet."

        whiptail --title "DNS Records Required" --msgbox "$DNS_MSG" 20 65
    fi
fi

# --- Admin Email ---
DEFAULT_EMAIL=""
[ "$IP_ONLY" = false ] && DEFAULT_EMAIL="admin@${DOMAIN}"

while true; do
    ADMIN_EMAIL=$(whiptail --title "Admin Email" --inputbox \
"Enter your admin email address.\n\
Used for SSL certificates and admin accounts." 10 60 "$DEFAULT_EMAIL" 3>&1 1>&2 2>&3) || true

    # Basic validation: non-empty and has @ with something on both sides
    if [[ "$ADMIN_EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]]; then
        break
    fi
    whiptail --title "Invalid Email" --msgbox \
    "Please enter a valid email address (e.g., you@example.com)." 8 60
done

# =============================================================================
# PASSWORDS
# =============================================================================
MARIADB_ROOT_PW=$(generate_password)
FLARUM_DB_PW=$(generate_password)
FLARUM_ADMIN_PW=$(generate_password)
GHOST_DB_PW=$(generate_password)
ZIPLINE_SECRET=$(generate_password)
ZIPLINE_DB_PW=$(generate_password)
MUMBLE_PW=$(generate_password)

# Customize passwords for selected services
if has_profile "forum"; then
    if whiptail --title "Flarum Admin" --yesno \
    "Set a custom Flarum admin password?\n(Otherwise one will be auto-generated)" 10 60; then
        FLARUM_ADMIN_PW=$(whiptail --title "Flarum Admin Password" --passwordbox \
        "Enter your Flarum forum admin password (min 8 characters):" 10 60 3>&1 1>&2 2>&3) || true
        if [ ${#FLARUM_ADMIN_PW} -lt 8 ]; then
            FLARUM_ADMIN_PW=$(generate_password)
            whiptail --title "Password" --msgbox "Password too short. Auto-generated one will be used." 8 60
        fi
    fi
fi

if has_profile "voice"; then
    if whiptail --title "Mumble Voice Chat" --yesno \
    "Set a custom Mumble SuperUser password?\n(Used to administer voice channels)" 10 60; then
        MUMBLE_PW=$(whiptail --title "Mumble SuperUser Password" --passwordbox \
        "Enter Mumble SuperUser password:" 10 60 3>&1 1>&2 2>&3) || true
    fi
fi

# =============================================================================
# WRITE CONFIG FILES
# =============================================================================

# Compute FLARUM_BASE_URL (full URL including subpath if applicable)
FLARUM_BASE_URL=""
if has_profile "forum" && [ -n "$FORUM_URL" ]; then
    if [[ "$FORUM_URL" == *"/"* ]]; then
        FLARUM_BASE_URL="https://${FORUM_URL}"
    else
        FLARUM_BASE_URL="https://${FORUM_URL}"
    fi
fi

# ---- Write .env ----
cat > "$ENV_FILE" << EOF
# Gaming Community in a Box — Generated by setup.sh
# $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Active service profiles (comma-separated)
COMPOSE_PROFILES=${PROFILES}

# Domain & routing
DOMAIN=${DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
STOAT_URL=${STOAT_URL}
FORUM_URL=${FORUM_URL}
GHOST_URL=${GHOST_URL}
ZIPLINE_URL=${ZIPLINE_URL}
PASTE_URL=${PASTE_URL}
ROOT_URL=${ROOT_URL}
ROOT_TARGET=${ROOT_TARGET}

# MariaDB (used by forum and blog)
MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PW}

# Flarum
FLARUM_DB_NAME=flarum
FLARUM_DB_USER=flarum
FLARUM_DB_PASSWORD=${FLARUM_DB_PW}
FLARUM_ADMIN_USER=admin
FLARUM_ADMIN_PASSWORD=${FLARUM_ADMIN_PW}
FLARUM_ADMIN_EMAIL=${ADMIN_EMAIL}
FLARUM_BASE_URL=${FLARUM_BASE_URL}

# Ghost
GHOST_DB_NAME=ghost
GHOST_DB_USER=ghost
GHOST_DB_PASSWORD=${GHOST_DB_PW}

# Zipline
ZIPLINE_CORE_SECRET=${ZIPLINE_SECRET}
ZIPLINE_DB_PASSWORD=${ZIPLINE_DB_PW}

# Mumble
MUMBLE_SUPERUSER_PASSWORD=${MUMBLE_PW}
EOF

chmod 600 "$ENV_FILE"

# ---- Create MariaDB init script (only matters if forum or blog enabled) ----
mkdir -p "$STACK_DIR/templates/initdb"
cat > "$STACK_DIR/templates/initdb/init.sql" << EOF
CREATE DATABASE IF NOT EXISTS \`flarum\`;
CREATE USER IF NOT EXISTS 'flarum'@'%' IDENTIFIED BY '${FLARUM_DB_PW}';
GRANT ALL PRIVILEGES ON \`flarum\`.* TO 'flarum'@'%';

CREATE DATABASE IF NOT EXISTS \`ghost\`;
CREATE USER IF NOT EXISTS 'ghost'@'%' IDENTIFIED BY '${GHOST_DB_PW}';
GRANT ALL PRIVILEGES ON \`ghost\`.* TO 'ghost'@'%';

FLUSH PRIVILEGES;
EOF

# ---- Generate Caddyfile ----
generate_caddyfile

# ---- Configure Stoat ----
whiptail --title "Setting up Stoat" --infobox \
"Configuring Stoat chat platform...\nThis generates encryption keys and config." 8 60

if [ -d "$STOAT_DIR" ]; then
    # Create shared Docker network for cross-compose communication
    docker network create evlbox 2>/dev/null || true

    cd "$STOAT_DIR"

    # Run Stoat's config generator non-interactively:
    #   - "y" = yes, behind another reverse proxy (our Caddy)
    #   - "y" = yes, enable camera/screen sharing
    if [ -f "$STOAT_DIR/generate_config.sh" ]; then
        printf 'y\ny\n' | bash "$STOAT_DIR/generate_config.sh" --overwrite "$STOAT_URL"
    fi

    # Replace Stoat's generated compose.override.yml with ours.
    # Stoat's own Caddy handles all internal path routing (/api, /ws, /autumn, etc.)
    # Our override just puts their Caddy on the shared evlbox network so our Caddy
    # can proxy to it. No .env.web or Revolt.toml patching needed — the generator's
    # "behind a proxy" output is correct as-is.
    cp "$STACK_DIR/templates/stoat-compose.override.yml" "$STOAT_DIR/compose.override.yml"
else
    echo "WARNING: Stoat directory not found at $STOAT_DIR"
    echo "Stoat should have been cloned during provisioning."
fi

# ---- Register Stoat as additional compose project for evlbox CLI ----
cat > "$STACK_DIR/.compose-projects" << 'EOF'
# Additional compose projects managed by this stack
/opt/evlbox/stoat/compose.yml
EOF

# ---- Save credentials file ----
CREDS_FILE="/root/evlbox-credentials.txt"
{
    echo "=== EVLBOX Gaming Community in a Box — Credentials ==="
    echo "Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    echo ""
    echo "Domain: ${DOMAIN}"
    echo "Admin Email: ${ADMIN_EMAIL}"
    echo "Enabled Services: Stoat${PROFILES:+, }${PROFILES//,/, }"
    echo ""
    echo "--- Service URLs ---"
    echo "Chat:         https://${STOAT_URL}"
    [ -n "$FORUM_URL" ]   && has_profile "forum"        && echo "Forum:        https://${FORUM_URL}"
    [ -n "$GHOST_URL" ]   && has_profile "blog"         && echo "Blog:         https://${GHOST_URL}"
    [ -n "$ZIPLINE_URL" ] && has_profile "screenshots"  && echo "Screenshots:  https://${ZIPLINE_URL}"
    [ -n "$PASTE_URL" ]   && has_profile "paste"        && echo "Paste:        https://${PASTE_URL}"
    has_profile "voice" && echo "Voice:        ${DOMAIN}:64738 (Mumble)"
    echo ""
    echo "--- Credentials ---"
    echo "Stoat:        Set up at https://${STOAT_URL}"
    [ -n "$FORUM_URL" ]   && has_profile "forum"        && echo "Flarum Admin: admin / ${FLARUM_ADMIN_PW}"
    has_profile "voice"   && echo "Mumble SuperUser: SuperUser / ${MUMBLE_PW}"
    [ -n "$GHOST_URL" ]   && has_profile "blog"         && echo "Ghost:        Set up at https://${GHOST_URL}/ghost"
    [ -n "$ZIPLINE_URL" ] && has_profile "screenshots"  && echo "Zipline:      Set up at https://${ZIPLINE_URL}"
    echo ""
    echo "--- Internal (do not share) ---"
    echo "MariaDB Root Password: ${MARIADB_ROOT_PW}"
    echo ""
    echo "DELETE THIS FILE after saving your credentials somewhere safe!"
} > "$CREDS_FILE"

chmod 600 "$CREDS_FILE"

# ---- Start services ----
echo ""
echo "Starting services... hang tight, this may take a few minutes."
echo "Do not close this terminal."
echo ""

echo "  Starting Stoat chat platform..."
cd "$STOAT_DIR"
docker compose up -d --quiet-pull 2>&1 | tail -1

echo "  Starting stack services..."
cd "$STACK_DIR"
docker compose up -d --quiet-pull 2>&1 | tail -1

echo ""

# ---- Build summary ----
SUMMARY="Your Gaming Community in a Box is running!\n\n"
SUMMARY+="Service URLs:\n"
SUMMARY+="  Chat:         https://${STOAT_URL}\n"
[ -n "$FORUM_URL" ]   && has_profile "forum"        && SUMMARY+="  Forum:        https://${FORUM_URL}\n"
[ -n "$GHOST_URL" ]   && has_profile "blog"         && SUMMARY+="  Blog:         https://${GHOST_URL}\n"
[ -n "$ZIPLINE_URL" ] && has_profile "screenshots"  && SUMMARY+="  Screenshots:  https://${ZIPLINE_URL}\n"
[ -n "$PASTE_URL" ]   && has_profile "paste"        && SUMMARY+="  Paste:        https://${PASTE_URL}\n"
has_profile "voice" && SUMMARY+="  Voice:        ${DOMAIN}:64738 (Mumble)\n"
SUMMARY+="\nCredentials saved to: /root/evlbox-credentials.txt\n"
SUMMARY+="Delete that file after saving your passwords!\n\n"
SUMMARY+="Run 'evlbox status' to check service health.\n"
SUMMARY+="Run 'evlbox enable <service>' to add services later.\n"
SUMMARY+="Run 'evlbox help' for more commands."

whiptail --title "Setup Complete!" --msgbox "$SUMMARY" 24 65
