#!/usr/bin/env bash
# Gaming Community in a Box — Phase 2: Setup Wizard
# Customer runs this on first SSH login (via `evlbox setup`).
# TUI wizard (whiptail) collects config, picks optional services, and starts everything.
# Safe to re-run: detects existing setup and offers reconfigure mode.

set -euo pipefail

STACK_DIR="/opt/evlbox/stack"
STOAT_DIR="/opt/evlbox/stoat"
ENV_FILE="$STACK_DIR/.env"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Please run as root: sudo evlbox setup"
        exit 1
    fi
}

check_whiptail() {
    if ! command -v whiptail &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq whiptail
    fi
}

has_profile() {
    [[ ",$PROFILES," == *",$1,"* ]]
}

had_profile() {
    [[ ",$OLD_PROFILES," == *",$1,"* ]]
}

is_new_profile() {
    has_profile "$1" && ! had_profile "$1"
}

get_server_ip() {
    hostname -I | awk '{print $1}'
}

# Validate that a URL does NOT contain a path (for apps that require subdomain)
validate_subdomain_only() {
    local url="$1"
    local app_name="$2"
    if [[ "$url" == *"/"* ]]; then
        whiptail --title "Invalid URL" --msgbox \
        "${app_name} requires its own subdomain and cannot run on a subpath.\n\n\
Example: chat.example.com (good)\n\
Example: example.com/chat (not supported)\n\n\
Please try again." 12 60
        return 1
    fi
    return 0
}

# Generate Caddyfile from per-service URL variables
generate_caddyfile() {
    local caddyfile="$STACK_DIR/templates/Caddyfile"

    cat > "$caddyfile" << 'HEADER'
# Gaming Community in a Box — Caddyfile
# Generated by setup.sh — do not edit directly.
# Re-run `evlbox setup` to regenerate.
HEADER

    # --- IP-only mode: single site block with self-signed TLS ---
    if [ "$IP_ONLY" = true ]; then
        cat >> "$caddyfile" << EOF

:443 {
	tls internal
	reverse_proxy stoat-caddy:80
}

:80 {
	reverse_proxy stoat-caddy:80
}
EOF
        return
    fi

    # --- Domain mode ---

    # Root domain — points to Stoat or Ghost depending on config
    if [ -n "${ROOT_URL:-}" ]; then
        if [ "$ROOT_TARGET" = "ghost" ]; then
            cat >> "$caddyfile" << EOF

${ROOT_URL} {
	reverse_proxy ghost:2368
}
EOF
        else
            cat >> "$caddyfile" << EOF

${ROOT_URL} {
	reverse_proxy stoat-caddy:80
}
EOF
        fi
    fi

    # Stoat chat subdomain (skip if same as ROOT_URL to avoid duplicate block)
    if [ "${STOAT_URL}" != "${ROOT_URL:-}" ]; then
        cat >> "$caddyfile" << EOF

${STOAT_URL} {
	reverse_proxy stoat-caddy:80
}
EOF
    fi

    # --- Forum (Flarum) — supports subdomain or subpath ---
    if has_profile "forum"; then
        if [[ "$FORUM_URL" == *"/"* ]]; then
            # Subpath mode: extract host and path
            local forum_host="${FORUM_URL%%/*}"
            local forum_path="/${FORUM_URL#*/}"
            cat >> "$caddyfile" << EOF

${forum_host} {
	handle_path ${forum_path}* {
		reverse_proxy flarum:8000
	}
}
EOF
        else
            cat >> "$caddyfile" << EOF

${FORUM_URL} {
	reverse_proxy flarum:8000
}
EOF
        fi
    fi

    # --- Ghost (blog) — subdomain only ---
    if has_profile "blog" && [ -n "${GHOST_URL:-}" ] && [ "${GHOST_URL}" != "${ROOT_URL:-}" ]; then
        cat >> "$caddyfile" << EOF

${GHOST_URL} {
	reverse_proxy ghost:2368
}
EOF
    fi

    # --- BookStack (wiki) — subdomain only ---
    if has_profile "wiki"; then
        cat >> "$caddyfile" << EOF

${BOOKSTACK_URL} {
	reverse_proxy bookstack:80
}
EOF
    fi

    # --- PrivateBin (paste) — supports subdomain or subpath ---
    if has_profile "paste"; then
        if [[ "$PASTE_URL" == *"/"* ]]; then
            local paste_host="${PASTE_URL%%/*}"
            local paste_path="/${PASTE_URL#*/}"
            cat >> "$caddyfile" << EOF

${paste_host} {
	handle_path ${paste_path}* {
		reverse_proxy privatebin:8080
	}
}
EOF
        else
            cat >> "$caddyfile" << EOF

${PASTE_URL} {
	reverse_proxy privatebin:8080
}
EOF
        fi
    fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
check_root
check_whiptail

cd "$STACK_DIR"

TERM=ansi
export TERM

# =============================================================================
# DETECT FIRST RUN vs RECONFIGURE
# =============================================================================
RECONFIGURE=false
FULL_RESET=false
OLD_PROFILES=""
OLD_DOMAIN=""

if [ -f "$ENV_FILE" ]; then
    # Existing install detected — load current values
    # shellcheck disable=SC1090
    source "$ENV_FILE"

    # Save old state for comparison
    OLD_PROFILES="${COMPOSE_PROFILES:-}"
    OLD_DOMAIN="${DOMAIN:-}"

    # Preserve all existing passwords/secrets from sourced .env
    OLD_MARIADB_ROOT_PW="${MARIADB_ROOT_PASSWORD:-}"
    OLD_FLARUM_DB_PW="${FLARUM_DB_PASSWORD:-}"
    OLD_GHOST_DB_PW="${GHOST_DB_PASSWORD:-}"
    OLD_BOOKSTACK_APP_KEY="${BOOKSTACK_APP_KEY:-}"
    OLD_BOOKSTACK_DB_PW="${BOOKSTACK_DB_PASSWORD:-}"
    OLD_MUMBLE_PW="${MUMBLE_SUPERUSER_PASSWORD:-}"

    # Preserve existing URL defaults for pre-filling
    OLD_STOAT_URL="${STOAT_URL:-}"
    OLD_FORUM_URL="${FORUM_URL:-}"
    OLD_GHOST_URL="${GHOST_URL:-}"
    OLD_BOOKSTACK_URL="${BOOKSTACK_URL:-}"
    OLD_PASTE_URL="${PASTE_URL:-}"
    OLD_ROOT_URL="${ROOT_URL:-}"
    OLD_ROOT_TARGET="${ROOT_TARGET:-stoat}"
    OLD_ADMIN_EMAIL="${ADMIN_EMAIL:-}"

    SETUP_MODE=$(whiptail --title "EVLBOX — Setup" --menu \
"An existing setup was detected.\nWhat would you like to do?" 12 65 2 \
"reconfigure" "Change services or domains" \
"reset"       "Full reset (destroys all data)" \
3>&1 1>&2 2>&3) || true

    if [ "$SETUP_MODE" = "reconfigure" ]; then
        RECONFIGURE=true
    elif [ "$SETUP_MODE" = "reset" ]; then
        CONFIRM=$(whiptail --title "⚠ FULL RESET — DATA LOSS" --inputbox \
"This will DESTROY ALL DATA including:\n\
  - Chat history and user accounts\n\
  - Forum posts and threads\n\
  - Wiki pages and content\n\
  - Blog posts\n\
  - All databases\n\n\
This CANNOT be undone.\n\n\
Type YES to confirm:" 18 65 "" 3>&1 1>&2 2>&3) || true

        if [ "$CONFIRM" != "YES" ]; then
            whiptail --title "Cancelled" --msgbox "Reset cancelled. Nothing was changed." 8 50
            exit 0
        fi
        FULL_RESET=true
    else
        exit 0
    fi
fi

# =============================================================================
# WELCOME (first run and full reset only)
# =============================================================================
if [ "$RECONFIGURE" = false ]; then
    whiptail --title "EVLBOX — Gaming Community in a Box" --msgbox \
"Welcome! This wizard will set up your gaming community server.\n\n\
You'll pick which services to run, configure your domain,\n\
and everything will be up and running in a few minutes.\n\n\
Includes: Stoat chat, forums, voice, wiki, and more." 12 65
fi

# =============================================================================
# SERVICE SELECTION
# =============================================================================

# Determine ON/OFF state for checklist based on existing profiles
forum_state="ON"; voice_state="ON"; wiki_state="ON"; paste_state="ON"; blog_state="OFF"
if [ "$RECONFIGURE" = true ]; then
    forum_state="OFF"; voice_state="OFF"; wiki_state="OFF"; paste_state="OFF"; blog_state="OFF"
    [[ ",$OLD_PROFILES," == *",forum,"* ]]  && forum_state="ON"
    [[ ",$OLD_PROFILES," == *",voice,"* ]]  && voice_state="ON"
    [[ ",$OLD_PROFILES," == *",wiki,"* ]]   && wiki_state="ON"
    [[ ",$OLD_PROFILES," == *",paste,"* ]]  && paste_state="ON"
    [[ ",$OLD_PROFILES," == *",blog,"* ]]   && blog_state="ON"
fi

SELECTED=$(whiptail --title "Choose Your Services" --checklist \
"Stoat (chat) is always installed. Pick your extras:\n\
Use SPACE to toggle, ENTER to confirm." 18 65 5 \
"forum"         "Flarum — Community forum"              "$forum_state" \
"voice"         "Mumble — Low-latency voice chat"       "$voice_state" \
"wiki"          "BookStack — Wiki, guides, and docs"    "$wiki_state" \
"paste"         "PrivateBin — Encrypted paste service"  "$paste_state" \
"blog"          "Ghost — Community blog / news"         "$blog_state" \
3>&1 1>&2 2>&3) || true

# Parse selections into comma-separated profile list
PROFILES=""
for item in $SELECTED; do
    item=$(echo "$item" | tr -d '"')
    if [ -z "$PROFILES" ]; then
        PROFILES="$item"
    else
        PROFILES="$PROFILES,$item"
    fi
done

# If nothing selected, that's fine — just Stoat
if [ -z "$PROFILES" ]; then
    whiptail --title "Minimal Install" --msgbox \
    "No optional services selected.\n\
Only Stoat (chat) will be installed.\n\
You can enable services later with: evlbox enable <service>" 10 60
fi

# =============================================================================
# DOMAIN & ROUTING
# =============================================================================
SERVER_IP=$(get_server_ip)
IP_ONLY=false
DOMAIN=""

# Initialize per-service URL variables (use old values as defaults in reconfigure)
STOAT_URL=""
FORUM_URL=""
GHOST_URL=""
BOOKSTACK_URL=""
PASTE_URL=""
ROOT_URL=""
ROOT_TARGET="stoat"

# Pre-fill defaults from existing config
DEFAULT_DOMAIN=""
if [ "$RECONFIGURE" = true ]; then
    DEFAULT_DOMAIN="$OLD_DOMAIN"
fi

# --- Step 1: Do you have a domain? ---
DOMAIN_CHOICE=$(whiptail --title "Domain Configuration" --menu \
"How would you like to access your services?" 14 65 2 \
"domain" "I have a domain (or will set one up)" \
"ip"     "No domain — IP-only mode" \
3>&1 1>&2 2>&3) || true

if [ "$DOMAIN_CHOICE" = "ip" ]; then
    IP_ONLY=true
    DOMAIN="$SERVER_IP"
    STOAT_URL="$SERVER_IP"
    # IP-only: disable all optional services, only Stoat runs
    PROFILES=""
    whiptail --title "IP-Only Mode" --msgbox \
"IP-only mode: only Stoat (chat) will run at https://${SERVER_IP}\n\
Other services need a domain for subdomain routing.\n\n\
Options to get a domain:\n\
  - Point your own domain at this IP\n\
  - EVLBOX customers: request a free yourname.evlbox.net\n\
    subdomain at https://evlbox.com/help\n\n\
Run 'evlbox setup' again after adding a domain to\n\
enable all services." 16 65
fi

# --- Step 2: Express or Custom? (only if they have a domain) ---
if [ "$IP_ONLY" = false ]; then
    ROUTING_MODE=$(whiptail --title "Routing Setup" --menu \
"How would you like to configure service URLs?" 12 65 2 \
"express" "Express setup (recommended) — auto-assign subdomains" \
"custom"  "Custom — choose URLs for each service" \
3>&1 1>&2 2>&3) || true

    # --- Express mode ---
    if [ "$ROUTING_MODE" = "express" ]; then
        DOMAIN=$(whiptail --title "Express Setup" --inputbox \
"Enter your domain (e.g., myguild.com):" 10 60 "$DEFAULT_DOMAIN" 3>&1 1>&2 2>&3) || true

        if [ -z "$DOMAIN" ]; then
            whiptail --title "Error" --msgbox "Domain cannot be empty." 8 40
            exit 1
        fi

        # Auto-assign subdomains
        STOAT_URL="chat.${DOMAIN}"
        has_profile "forum"        && FORUM_URL="forum.${DOMAIN}"
        has_profile "wiki"         && BOOKSTACK_URL="wiki.${DOMAIN}"
        has_profile "paste"        && PASTE_URL="paste.${DOMAIN}"

        if has_profile "blog"; then
            GHOST_URL="${DOMAIN}"
            ROOT_URL="${DOMAIN}"
            ROOT_TARGET="ghost"
        else
            ROOT_URL="${DOMAIN}"
            ROOT_TARGET="stoat"
        fi

        # Build DNS records message
        DNS_MSG="Create these DNS records pointing to ${SERVER_IP}:\n\n"
        DNS_MSG+="  A  ${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="  A  chat.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "forum"        && DNS_MSG+="  A  forum.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "wiki"         && DNS_MSG+="  A  wiki.${DOMAIN}  →  ${SERVER_IP}\n"
        has_profile "paste"        && DNS_MSG+="  A  paste.${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="\nOr use a wildcard:\n"
        DNS_MSG+="  A  *.${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="  A  ${DOMAIN}  →  ${SERVER_IP}\n"
        DNS_MSG+="\nCaddy will retry automatically if DNS isn't ready yet."

        whiptail --title "DNS Records Required" --msgbox "$DNS_MSG" 22 65

    # --- Custom mode ---
    elif [ "$ROUTING_MODE" = "custom" ]; then
        DOMAIN=$(whiptail --title "Base Domain" --inputbox \
"Enter your base domain (used for SSL and routing):" 10 60 "$DEFAULT_DOMAIN" 3>&1 1>&2 2>&3) || true

        if [ -z "$DOMAIN" ]; then
            whiptail --title "Error" --msgbox "Domain cannot be empty." 8 40
            exit 1
        fi

        # Stoat — subdomain required
        local_stoat_default="${OLD_STOAT_URL:-chat.${DOMAIN}}"
        while true; do
            STOAT_URL=$(whiptail --title "Stoat Chat [subdomain required]" --inputbox \
"Enter URL for Stoat chat.\n\
Stoat MUST have its own subdomain (no subpaths).\n\n\
Example: chat.${DOMAIN}" 12 60 "$local_stoat_default" 3>&1 1>&2 2>&3) || true
            validate_subdomain_only "$STOAT_URL" "Stoat" && break
        done

        # Forum (Flarum) — subdomain or subpath
        if has_profile "forum"; then
            local_forum_default="${OLD_FORUM_URL:-forum.${DOMAIN}}"
            FORUM_URL=$(whiptail --title "Flarum Forum [subdomain or subpath]" --inputbox \
"Enter URL for Flarum forum.\n\
Supports subdomain OR subpath.\n\n\
Examples: forum.${DOMAIN} or ${DOMAIN}/forum" 12 60 "$local_forum_default" 3>&1 1>&2 2>&3) || true
        fi

        # Ghost — subdomain required
        if has_profile "blog"; then
            local_ghost_default="${OLD_GHOST_URL:-${DOMAIN}}"
            while true; do
                GHOST_URL=$(whiptail --title "Ghost Blog [subdomain required]" --inputbox \
"Enter URL for Ghost blog.\n\
Ghost MUST have its own subdomain (no subpaths).\n\n\
Example: ${DOMAIN} or blog.${DOMAIN}" 12 60 "$local_ghost_default" 3>&1 1>&2 2>&3) || true
                validate_subdomain_only "$GHOST_URL" "Ghost" && break
            done
        fi

        # BookStack — subdomain required
        if has_profile "wiki"; then
            local_wiki_default="${OLD_BOOKSTACK_URL:-wiki.${DOMAIN}}"
            while true; do
                BOOKSTACK_URL=$(whiptail --title "BookStack Wiki [subdomain required]" --inputbox \
"Enter URL for BookStack wiki.\n\
BookStack MUST have its own subdomain (no subpaths).\n\n\
Example: wiki.${DOMAIN}" 12 60 "$local_wiki_default" 3>&1 1>&2 2>&3) || true
                validate_subdomain_only "$BOOKSTACK_URL" "BookStack" && break
            done
        fi

        # PrivateBin — subdomain or subpath
        if has_profile "paste"; then
            local_paste_default="${OLD_PASTE_URL:-paste.${DOMAIN}}"
            PASTE_URL=$(whiptail --title "PrivateBin Paste [subdomain or subpath]" --inputbox \
"Enter URL for PrivateBin.\n\
Supports subdomain OR subpath.\n\n\
Examples: paste.${DOMAIN} or ${DOMAIN}/paste" 12 60 "$local_paste_default" 3>&1 1>&2 2>&3) || true
        fi

        # Determine root domain target
        if has_profile "blog" && [ "$GHOST_URL" = "$DOMAIN" ]; then
            ROOT_URL="$DOMAIN"
            ROOT_TARGET="ghost"
        else
            ROOT_URL="$DOMAIN"
            ROOT_TARGET="stoat"
        fi

        # Collect all unique hostnames for DNS records
        DNS_MSG="Create these DNS records pointing to ${SERVER_IP}:\n\n"
        declare -A dns_hosts
        dns_hosts["$DOMAIN"]=1
        dns_hosts["${STOAT_URL}"]=1
        [ -n "$FORUM_URL" ] && dns_hosts["${FORUM_URL%%/*}"]=1
        [ -n "$GHOST_URL" ] && dns_hosts["${GHOST_URL}"]=1
        [ -n "$BOOKSTACK_URL" ] && dns_hosts["${BOOKSTACK_URL}"]=1
        [ -n "$PASTE_URL" ] && dns_hosts["${PASTE_URL%%/*}"]=1

        for host in "${!dns_hosts[@]}"; do
            DNS_MSG+="  A  ${host}  →  ${SERVER_IP}\n"
        done
        DNS_MSG+="\nCaddy will retry automatically if DNS isn't ready yet."

        whiptail --title "DNS Records Required" --msgbox "$DNS_MSG" 20 65
    fi
fi

# --- Admin Email ---
DEFAULT_EMAIL="${OLD_ADMIN_EMAIL:-}"
[ -z "$DEFAULT_EMAIL" ] && [ "$IP_ONLY" = false ] && DEFAULT_EMAIL="admin@${DOMAIN}"

while true; do
    ADMIN_EMAIL=$(whiptail --title "Admin Email" --inputbox \
"Enter your admin email address.\n\
Used for SSL certificates and admin accounts." 10 60 "$DEFAULT_EMAIL" 3>&1 1>&2 2>&3) || true

    # Basic validation: non-empty and has @ with something on both sides
    if [[ "$ADMIN_EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]]; then
        break
    fi
    whiptail --title "Invalid Email" --msgbox \
    "Please enter a valid email address (e.g., you@example.com)." 8 60
done

# =============================================================================
# PASSWORDS — preserve existing, generate only for new services
# =============================================================================
if [ "$RECONFIGURE" = true ]; then
    # Preserve all existing passwords
    MARIADB_ROOT_PW="$OLD_MARIADB_ROOT_PW"
    FLARUM_DB_PW="$OLD_FLARUM_DB_PW"
    FLARUM_ADMIN_PW=""  # not stored in .env — only set on first install of forum
    GHOST_DB_PW="$OLD_GHOST_DB_PW"
    BOOKSTACK_APP_KEY="$OLD_BOOKSTACK_APP_KEY"
    BOOKSTACK_DB_PW="$OLD_BOOKSTACK_DB_PW"
    MUMBLE_PW="$OLD_MUMBLE_PW"
    BOOKSTACK_ADMIN_PW=""  # not stored in .env, only used on first setup

    # MariaDB root — always needed, generate if somehow missing
    [ -z "$MARIADB_ROOT_PW" ] && MARIADB_ROOT_PW=$(generate_password)

    # Generate fresh passwords for newly enabled services only
    if is_new_profile "forum"; then
        FLARUM_DB_PW=$(generate_password)
        FLARUM_ADMIN_PW=$(generate_password)
    fi
    if is_new_profile "blog"; then
        GHOST_DB_PW=$(generate_password)
    fi
    if is_new_profile "wiki"; then
        BOOKSTACK_APP_KEY="base64:$(openssl rand -base64 32)"
        BOOKSTACK_DB_PW=$(generate_password)
        BOOKSTACK_ADMIN_PW=$(generate_password)
    fi
    if is_new_profile "voice"; then
        MUMBLE_PW=$(generate_password)
    fi

else
    # First run or full reset — generate everything fresh
    MARIADB_ROOT_PW=$(generate_password)
    FLARUM_DB_PW=$(generate_password)
    FLARUM_ADMIN_PW=$(generate_password)
    GHOST_DB_PW=$(generate_password)
    BOOKSTACK_DB_PW=$(generate_password)
    BOOKSTACK_APP_KEY="base64:$(openssl rand -base64 32)"
    BOOKSTACK_ADMIN_PW=$(generate_password)
    MUMBLE_PW=$(generate_password)

fi

# =============================================================================
# WRITE CONFIG FILES
# =============================================================================

# Compute FLARUM_BASE_URL (full URL including subpath if applicable)
FLARUM_BASE_URL=""
if has_profile "forum" && [ -n "$FORUM_URL" ]; then
    FLARUM_BASE_URL="https://${FORUM_URL}"
fi

# ---- Write .env ----
cat > "$ENV_FILE" << EOF
# Gaming Community in a Box — Generated by setup.sh
# $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Active service profiles (comma-separated)
COMPOSE_PROFILES=${PROFILES}

# Domain & routing
DOMAIN=${DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
STOAT_URL=${STOAT_URL}
FORUM_URL=${FORUM_URL}
GHOST_URL=${GHOST_URL}
BOOKSTACK_URL=${BOOKSTACK_URL}
PASTE_URL=${PASTE_URL}
ROOT_URL=${ROOT_URL}
ROOT_TARGET=${ROOT_TARGET}

# MariaDB (used by forum, blog, wiki)
MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PW}

# Flarum
FLARUM_DB_NAME=flarum
FLARUM_DB_USER=flarum
FLARUM_DB_PASSWORD=${FLARUM_DB_PW}
FLARUM_BASE_URL=${FLARUM_BASE_URL}

# Ghost
GHOST_DB_NAME=ghost
GHOST_DB_USER=ghost
GHOST_DB_PASSWORD=${GHOST_DB_PW}

# BookStack
BOOKSTACK_APP_KEY=${BOOKSTACK_APP_KEY}
BOOKSTACK_DB_NAME=bookstack
BOOKSTACK_DB_USER=bookstack
BOOKSTACK_DB_PASSWORD=${BOOKSTACK_DB_PW}

# Mumble
MUMBLE_SUPERUSER_PASSWORD=${MUMBLE_PW}
EOF

chmod 600 "$ENV_FILE"

# ---- Create MariaDB init script (idempotent — safe to regenerate) ----
mkdir -p "$STACK_DIR/templates/initdb"
cat > "$STACK_DIR/templates/initdb/init.sql" << EOF
CREATE DATABASE IF NOT EXISTS \`flarum\`;
CREATE USER IF NOT EXISTS 'flarum'@'%' IDENTIFIED BY '${FLARUM_DB_PW}';
ALTER USER 'flarum'@'%' IDENTIFIED BY '${FLARUM_DB_PW}';
GRANT ALL PRIVILEGES ON \`flarum\`.* TO 'flarum'@'%';

CREATE DATABASE IF NOT EXISTS \`ghost\`;
CREATE USER IF NOT EXISTS 'ghost'@'%' IDENTIFIED BY '${GHOST_DB_PW}';
ALTER USER 'ghost'@'%' IDENTIFIED BY '${GHOST_DB_PW}';
GRANT ALL PRIVILEGES ON \`ghost\`.* TO 'ghost'@'%';

CREATE DATABASE IF NOT EXISTS \`bookstack\`;
CREATE USER IF NOT EXISTS 'bookstack'@'%' IDENTIFIED BY '${BOOKSTACK_DB_PW}';
ALTER USER 'bookstack'@'%' IDENTIFIED BY '${BOOKSTACK_DB_PW}';
GRANT ALL PRIVILEGES ON \`bookstack\`.* TO 'bookstack'@'%';

FLUSH PRIVILEGES;
EOF

# ---- Generate Caddyfile (always safe to regenerate) ----
generate_caddyfile

# ---- Configure Stoat ----
if [ -d "$STOAT_DIR" ]; then
    # Create shared Docker network for cross-compose communication
    docker network create evlbox 2>/dev/null || true

    if [ "$RECONFIGURE" = true ] && [ "$DOMAIN" = "$OLD_DOMAIN" ]; then
        # Domain unchanged — don't touch Stoat config, just ensure override is current
        cp "$STACK_DIR/templates/stoat-compose.override.yml" "$STOAT_DIR/compose.override.yml"
    else
        # First run, full reset, or domain changed — run Stoat's config generator
        whiptail --title "Setting up Stoat" --infobox \
        "Configuring Stoat chat platform...\nThis generates encryption keys and config." 8 60

        cd "$STOAT_DIR"

        # Run Stoat's config generator non-interactively:
        #   - "y" = yes, behind another reverse proxy (our Caddy)
        #   - "y" = yes, enable camera/screen sharing
        if [ -f "$STOAT_DIR/generate_config.sh" ]; then
            printf 'y\ny\n' | bash "$STOAT_DIR/generate_config.sh" --overwrite "$STOAT_URL"
        fi

        # Replace Stoat's generated compose.override.yml with ours.
        # Stoat's own Caddy handles all internal path routing (/api, /ws, /autumn, etc.)
        # Our override just puts their Caddy on the shared evlbox network so our Caddy
        # can proxy to it. No .env.web or Revolt.toml patching needed — the generator's
        # "behind a proxy" output is correct as-is.
        cp "$STACK_DIR/templates/stoat-compose.override.yml" "$STOAT_DIR/compose.override.yml"
    fi
else
    echo "WARNING: Stoat directory not found at $STOAT_DIR"
    echo "Stoat should have been cloned during provisioning."
fi

# ---- Register Stoat as additional compose project for evlbox CLI ----
cat > "$STACK_DIR/.compose-projects" << 'EOF'
# Additional compose projects managed by this stack
/opt/evlbox/stoat/compose.yml
EOF

# ---- Save credentials file ----
CREDS_FILE="/root/evlbox-credentials.txt"
{
    echo "=== EVLBOX Gaming Community in a Box — Credentials ==="
    echo "Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    echo ""
    echo "Domain: ${DOMAIN}"
    echo "Admin Email: ${ADMIN_EMAIL}"
    echo "Enabled Services: Stoat${PROFILES:+, }${PROFILES//,/, }"
    echo ""
    echo "--- Service URLs ---"
    echo "Chat:         https://${STOAT_URL}"
    [ -n "$FORUM_URL" ]     && has_profile "forum"  && echo "Forum:        https://${FORUM_URL}"
    [ -n "$GHOST_URL" ]     && has_profile "blog"   && echo "Blog:         https://${GHOST_URL}"
    [ -n "$BOOKSTACK_URL" ] && has_profile "wiki"   && echo "Wiki:         https://${BOOKSTACK_URL}"
    [ -n "$PASTE_URL" ]     && has_profile "paste"  && echo "Paste:        https://${PASTE_URL}"
    has_profile "voice" && echo "Voice:        ${DOMAIN}:64738 (Mumble)"
    echo ""
    echo "--- Credentials ---"
    echo "Stoat:        Set up at https://${STOAT_URL}"
    [ -n "$FORUM_URL" ]     && has_profile "forum"  && [ -n "$FLARUM_ADMIN_PW" ] && echo "Flarum Admin: admin / ${FLARUM_ADMIN_PW}"
    has_profile "voice"     && echo "Mumble SuperUser: SuperUser / ${MUMBLE_PW}"
    [ -n "$GHOST_URL" ]     && has_profile "blog"   && echo "Ghost:        Set up at https://${GHOST_URL}/ghost"
    [ -n "$BOOKSTACK_URL" ] && has_profile "wiki"   && [ -n "$BOOKSTACK_ADMIN_PW" ] && echo "BookStack:    ${ADMIN_EMAIL} / ${BOOKSTACK_ADMIN_PW}"
    echo ""
    echo "--- Internal (do not share) ---"
    echo "MariaDB Root Password: ${MARIADB_ROOT_PW}"
    echo ""
    echo "DELETE THIS FILE after saving your credentials somewhere safe!"
} > "$CREDS_FILE"

chmod 600 "$CREDS_FILE"

# ---- Start services ----
echo ""
echo "Starting services... hang tight, this may take a few minutes."
echo "Do not close this terminal."
echo ""

echo "  Stopping existing services..."
cd "$STOAT_DIR"
if [ "$FULL_RESET" = true ]; then
    docker compose down -v --remove-orphans 2>/dev/null || true
    # Stoat uses bind mounts under ./data/ — must rm explicitly
    rm -rf "$STOAT_DIR/data"
else
    docker compose down --remove-orphans 2>/dev/null || true
fi
cd "$STACK_DIR"
if [ "$FULL_RESET" = true ]; then
    docker compose down -v --remove-orphans 2>/dev/null || true
else
    docker compose down --remove-orphans 2>/dev/null || true
fi

echo "  Starting Stoat chat platform..."
cd "$STOAT_DIR"
docker compose up -d --quiet-pull 2>&1 | tail -1

echo "  Starting stack services..."
cd "$STACK_DIR"
docker compose up -d --quiet-pull 2>&1 | tail -1

# ---- Reset BookStack default admin credentials (first run / new wiki only) ----
if [ "$RECONFIGURE" = false ] || is_new_profile "wiki"; then
    if has_profile "wiki" && [ -n "$BOOKSTACK_ADMIN_PW" ]; then
        echo "  Waiting for BookStack to initialize..."
        # Wait for MariaDB to be accepting connections
        for i in $(seq 1 30); do
            docker compose exec -T mariadb mariadb -u root -p"${MARIADB_ROOT_PW}" \
                -e "SELECT 1" >/dev/null 2>&1 && break
            sleep 2
        done
        # Wait for BookStack's linuxserver init to create storage directories
        for i in $(seq 1 60); do
            docker compose exec -T bookstack test -d /app/www/storage/logs \
                >/dev/null 2>&1 && break
            sleep 2
        done
        # Now run artisan — retry up to 30x in case DB migrations are still running
        for i in $(seq 1 30); do
            docker compose exec -T bookstack php /app/www/artisan bookstack:create-admin \
                --email="$ADMIN_EMAIL" --name="Admin" --password="$BOOKSTACK_ADMIN_PW" --initial \
                >/dev/null 2>&1 && break
            sleep 3
        done
    fi
fi

# ---- Set Flarum admin credentials post-install (first run / new forum only) ----
# crazymax/flarum ignores env vars for admin — always creates user "flarum" / "flarum".
# We update it directly in MariaDB after Flarum has run its install migrations.
if [ "$RECONFIGURE" = false ] || is_new_profile "forum"; then
    if has_profile "forum"; then
        echo "  Waiting for Flarum to initialize..."
        # Wait for Flarum's users table to be populated (install complete)
        for i in $(seq 1 90); do
            docker compose exec -T mariadb mariadb -u root -p"${MARIADB_ROOT_PW}" \
                -e "SELECT 1 FROM flarum.flarum_users LIMIT 1" >/dev/null 2>&1 && break
            sleep 3
        done
        # Generate bcrypt hash via PHP inside the flarum container
        FLARUM_HASH=$(docker compose exec -T flarum php -r \
            "echo password_hash('${FLARUM_ADMIN_PW}', PASSWORD_BCRYPT);" 2>/dev/null) || true
        if [ -n "$FLARUM_HASH" ]; then
            docker compose exec -T mariadb mariadb -u root -p"${MARIADB_ROOT_PW}" \
                -e "UPDATE flarum.flarum_users SET username='admin', email='${ADMIN_EMAIL}', password='${FLARUM_HASH}' WHERE id=1;" \
                >/dev/null 2>&1 || true
        fi
    fi
fi

echo ""
echo "=================================================="
echo "  Setup Complete!"
echo "=================================================="
echo ""
echo "Service URLs:"
echo "  Chat:         https://${STOAT_URL}"
[ -n "$FORUM_URL" ]     && has_profile "forum"  && echo "  Forum:        https://${FORUM_URL}"
[ -n "$GHOST_URL" ]     && has_profile "blog"   && echo "  Blog:         https://${GHOST_URL}"
[ -n "$BOOKSTACK_URL" ] && has_profile "wiki"   && echo "  Wiki:         https://${BOOKSTACK_URL}"
[ -n "$PASTE_URL" ]     && has_profile "paste"  && echo "  Paste:        https://${PASTE_URL}"
has_profile "voice" && echo "  Voice:        ${DOMAIN}:64738 (Mumble)"
echo ""
echo "Credentials saved to: /root/evlbox-credentials.txt"
echo "Delete that file after saving your passwords!"
echo ""
echo "Run 'evlbox status' to check service health."
echo "=================================================="
echo ""
